baseURL = 'https://example.org/'

# Multilingual configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = "Your Space"
    contentDir = 'content/en'
    weight = 1
    
    [languages.en.params]
      name = "Your Name"
    
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10

      [[languages.en.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 20

      [[languages.en.menus.main]]
        name = 'Projects'
        pageRef = '/projects'
        weight = 30
  
  [languages.zh]
    languageCode = 'zh'
    languageName = '中文'
    title = "你的空间"
    contentDir = 'content/zh'
    weight = 2
    
    [languages.zh.params]
      name = "你的名字"
    
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        name = '首页'
        pageRef = '/'
        weight = 10

      [[languages.zh.menus.main]]
        name = '文章'
        pageRef = '/posts'
        weight = 20

      [[languages.zh.menus.main]]
        name = '项目'
        pageRef = '/projects'
        weight = 30

[params]
  researchField = "Your Research Field"
  
  [[params.social]]
    name = "GitHub"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    # url = 

  [[params.social]]
    name = "Bilibili"
    icon = "fa-brands fa-bilibili fa-2x"
    weight = 2
    # url = 

  [[params.social]]
    name = "Email"
    icon = "fa-solid fa-envelope fa-2x"
    weight = 3
    # url = 


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
